"""Windows .exe version-resource generator for Sizeamatic Pro's build.

Generates the version-info file PyInstaller's `EXE(version=...)`
consumes to embed a real Windows version resource into the built
`.exe` — the "File version"/"Product version" fields visible in
Explorer's file Properties dialog (ROADMAP.md Phase 9). Read directly
from `pyproject.toml`'s version at build time (via `sizeamatic.spec`)
rather than a separately maintained constant, so there's exactly one
place the version number lives.

Usage:
    uv run python build_version_info.py 0.1.0 version_info.txt

Author:
    Isaac Travers

Date:
    2026-08-12
"""

import argparse

# PyInstaller execs a version-info file in a namespace where
# VSVersionInfo/FixedFileInfo/StringFileInfo/StringTable/StringStruct/
# VarFileInfo/VarStruct are already available as globals (the same way
# a .spec file gets Analysis/EXE/etc. injected) - the generated file
# below deliberately has no imports of its own, matching that contract.
VERSION_FILE_TEMPLATE = """# UTF-8
#
# Auto-generated by build_version_info.py from pyproject.toml's version
# at build time - do not edit by hand, it will be overwritten on the
# next build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({v0}, {v1}, {v2}, 0),
    prodvers=({v0}, {v1}, {v2}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u"040904B0",
          [StringStruct(u"CompanyName", u"Marine Applied Research & Exploration"),
           StringStruct(u"FileDescription", u"Sizeamatic Pro"),
           StringStruct(u"FileVersion", u"{version}"),
           StringStruct(u"ProductName", u"Sizeamatic Pro"),
           StringStruct(u"ProductVersion", u"{version}")],
        )
      ]
    ),
    VarFileInfo([VarStruct(u"Translation", [1033, 1200])]),
  ],
)
"""


def parse_version_tuple(version_str):
    """Parse a "X.Y.Z"-style version string into a 3-tuple of ints.

    Windows version resources need plain integers - this tolerates
    trailing pre-release/build suffixes (e.g. "0.1.0rc1") by taking only
    each dot-separated part's leading digits, and pads missing parts
    with 0 rather than raising, since a version string is never
    guaranteed to have exactly 3 numeric components.

    Args:
        version_str (str): The version string (e.g. "0.1.0").

    Returns:
        tuple[int, int, int]: The parsed (major, minor, patch) tuple.
    """
    parts = version_str.split(".")
    nums = []
    for part in parts[:3]:
        digits = ""
        for ch in part:
            if ch.isdigit():
                digits += ch
            else:
                break
        nums.append(int(digits) if digits else 0)
    while len(nums) < 3:
        nums.append(0)
    return tuple(nums)


def write_version_file(version_str, output_path):
    """Write a PyInstaller Windows version-resource file.

    Args:
        version_str (str): The app version string (e.g. "0.1.0").
        output_path (str): Path to write the generated version-info
            file to.

    Returns:
        None
    """
    v0, v1, v2 = parse_version_tuple(version_str)
    content = VERSION_FILE_TEMPLATE.format(v0=v0, v1=v1, v2=v2, version=version_str)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    """Parse CLI arguments and write a version-info file.

    Returns:
        None
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help='App version string, e.g. "0.1.0".')
    parser.add_argument("output_path", help="Path to write the version-info file to.")
    args = parser.parse_args()

    write_version_file(args.version, args.output_path)
    print(f"Wrote {args.output_path}")


if __name__ == "__main__":
    main()
